trigger:
  branches:
    include:
      - main  # Run pipeline on main branch push

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux build agent

steps:
  - task: UseNode@1
    inputs:
      version: '20.x'  # Specify Node.js version

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build project'

  - script: npm test
    displayName: 'Run tests'
